# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 07:03
from __future__ import unicode_literals

import billing.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='billPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payType', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ('id', 'date'),
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ('id', 'date'),
            },
        ),
        migrations.CreateModel(
            name='Roommate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('isactive', models.BooleanField(default=True)),
                ('utilpercentowed', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('utiltotalowed', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('utiltotaldebt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('utiltotalpaid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('utiltotalremaining', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('ioutotalowed', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('ioutotaldebt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('ioutotalpaid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('ioutotalremaining', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('house', models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='billing.Lease')),
                ('user', models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='userPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payType', models.CharField(max_length=25)),
                ('house', models.ForeignKey(db_constraint=False, default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='billing.Lease')),
                ('payee', models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='payee', to='billing.Roommate')),
                ('payer', models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='payer', to='billing.Roommate')),
            ],
            options={
                'ordering': ('id', 'date'),
            },
        ),
        migrations.CreateModel(
            name='userSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venmoAcct', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('phonenumber', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('user', models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id', 'user'),
            },
        ),
        migrations.CreateModel(
            name='UtilityBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dueDate', models.DateField(blank=True, null=True)),
                ('statementDate', models.DateField(blank=True, null=True)),
                ('datepaid', models.DateField(blank=True, default='', null=True)),
                ('billdoc', models.FileField(blank=True, default=' ', max_length=144, null=True, upload_to=billing.models.bill_directory_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('house', models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='billing.Lease')),
                ('owner', models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='billing.Roommate')),
            ],
            options={
                'ordering': ('id', 'dueDate'),
            },
        ),
        migrations.CreateModel(
            name='UtilityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('website', models.CharField(max_length=200)),
                ('serviceType', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, max_length=144, null=True, upload_to='uploads/utilityImgs')),
            ],
            options={
                'ordering': ('id', 'name'),
            },
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='utilType',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='billing.UtilityType'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='UtilBill',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='billing.UtilityBill'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='house',
            field=models.ForeignKey(db_constraint=False, default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='billing.Lease'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='requestee',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='requestee', to='billing.Roommate'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='requester',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='requester', to='billing.Roommate'),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='UtilBill',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='billing.UtilityBill'),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='payer',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='billing.Roommate'),
        ),
    ]
