# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommate',
            name='percentowed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='roommate',
            name='totalowed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='roommate',
            name='totalpaid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='payType',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='lease',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='payType',
            field=models.CharField(max_length=25),
        ),
    ]
