# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20170319_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('UtilBill', models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='billing.UtilityBill')),
            ],
            options={
                'ordering': ('id', 'date'),
            },
        ),
        migrations.AddField(
            model_name='roommate',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='requestee',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='requestee', to='billing.Roommate'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='requester',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='requester', to='billing.Roommate'),
        ),
    ]
