# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20170320_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='house',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='billing.Lease'),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='datepaid',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
