# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_paymentrequest_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='house',
            field=models.ForeignKey(db_constraint=False, default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='billing.Lease'),
        ),
    ]
