# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20170323_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='house',
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='house',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='billing.Lease'),
        ),
    ]
